version: 2.1
# configure the pipeline
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
# the commands we want to run
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install # install node
      - checkout # make sure node is working
      - aws-cli/setup # install aws cli
      - eb/setup # install eb cli
      - run:
          name: "Checking Versions"
          command: |
            node --version
      - run:
          name: "Say Hello"
          command: |
            echo "Hello Universe"
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Back-End Test
          command: |
            npm run backend:test
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
      
# do the build job only if the main branch is triggered
workflows:
  basic-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main