version: 2.1
orbs: # declaring the orbs for setting up the servers and softwares during the CI/CD process.
  node: circleci/node@5.0.1 # setup node.js on the server.
  aws-cli: circleci/aws-cli@3.0.0 # setup aws cli on the server.
  eb: circleci/aws-elastic-beanstalk@2.0.1 # set up eb on the server.
jobs: # For running a series of steps that run a series of commands.
  CI_CD:
    docker: # Specify the primary container image.
      - image: "cimg/base:stable"
    steps: # A collection of excutable commands required to complete your job.
      - node/install # install node.
      - checkout # check the source code.
      - aws-cli/setup # install aws cli.
      - eb/setup # install eb cli.
      - run:
          name: "Checking Versions"
          command: |
            node --version
      - run:
          name: "Say Hello"
          command: |
            echo "Hello Universe"
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      - run:
          name: Back-End Test
          command: |
            npm run backend:test
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
workflows: # For orchestrating the jobs.
  udagram:
    jobs:
      - CI_CD:
          filters:  
            branches: 
              only: master # To make sure that the pipeline will only run on the master branch.